More workflow fixes

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,22 +1,22 @@
 name: Linting
 on:
-    pull_request:
+  pull_request:
 jobs:
-    lint:
-        name: Lint
-        runs-on: ubuntu-latest
-        steps:
-        - uses: actions/checkout@v1
-        - uses: ZedThree/clang-tidy-review@v0.12.0
-            id: review
-            with:
-                apt_packages: libunwind-dev libglfw3-dev
-                cmake_command: cmake .
+  lint:
+    name: Lint
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v1
+    - uses: ZedThree/clang-tidy-review@v0.12.0
+      id: review
+      with:
+        apt_packages: libunwind-dev libglfw3-dev
+        cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
 
-        # Uploads an artefact containing clang_fixes.json
-        - uses: ZedThree/clang-tidy-review/upload@v0.12.0
-            id: upload-review
+    # Uploads an artefact containing clang_fixes.json
+    - uses: ZedThree/clang-tidy-review/upload@v0.12.0
+      id: upload-review
 
-        # If there are any comments, fail the check
-        - if: steps.review.outputs.total_comments > 0
-            run: exit 1
+    # If there are any comments, fail the check
+    - if: steps.review.outputs.total_comments > 0
+      run: exit 1
